spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: flzx3+Qc
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 设置mp的全局配置
  global-config:
    db-config:
      table-prefix: t_
      # 设置统一的主键生成策略
      id-type: auto
      logic-delete-field: isDeleted
  # 扫描通用枚举的包
  type-enums-package: com.qc.mp.enums