spring:
  # 配置数据源信息
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组，默认值是master
      primary: master
      # 严格匹配数据源，默认是false，true未匹配到指定数据源时抛异常，false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: flzx3+Qc
        slave_1:
          url: jdbc:mysql://localhost:3306/mybatis_plus_1?characterEncoding=utf8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: flzx3+Qc
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 设置mp的全局配置
  global-config:
    db-config:
      table-prefix: t_
      # 设置统一的主键生成策略
      id-type: auto
      logic-delete-field: isDeleted
  # 扫描通用枚举的包
  type-enums-package: com.qc.mp.enums